// Code generated by Slice Machine. DO NOT EDIT.

import Member from "./Member/index.svelte";
import Members from "./Members/index.svelte";
import Squad from "./Squad/index.svelte";
import Squads from "./Squads/index.svelte";

export const components = {
  member: Member,
  memberslist: Members,
  squad: Squad,
  squadlist: Squads,
};
