// Code generated by Slice Machine. DO NOT EDIT.

import Memberslist from "./Memberslist/index.svelte";
import Squadslist from "./Squadslist/index.svelte";

export const components = {
  memberslist: Memberslist,
  squadlist: Squadslist,
};
